config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
# envは環境を確認するメソッド。↓はRailsが開発環境であるかを確認する。
  if Rails.env.development?
# letter_opener_webが送信されたメールを見れるようにしてくれる。
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  get 'comments/edit'
  root to: 'home#index'
  resources :pictures, shallow: true do
    collection do
      get :search
    end
    resources :comments
  end
  get    '/welcome', to: "sessions#new",     as: :welcome
  post   '/login',   to: "sessions#create",  as: :login
  delete '/logout',  to: "sessions#destroy", as: :logout
  resources :users, only: %i[index new create show]
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    patch :read, on: :member
  end
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture
# 別のモデルとの１対１の関連付けを行い、オプションをつけることもできる。as:でポリモーフィック関連を定義することができる。
  has_one :activity, as: :subject, dependent: :destroy

  validates :body, presence: true, length: { maximum: 1000 }

# Commentがcreateされる時には必ずcreate_activitiesが実行される。
  after_create_commit :create_activities

  private

# ポリモーフィックをしているので、Activityクラスのインスタンスを使うことができる。
  def create_activities
    Activity.create(subject: self, user: picture.user, action_type: :commented_to_own_picture)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    UserMailer.with(user_from: current_user, user_to: @comment.picture.user, comment: @comment).comment_picture.deliver_later if @comment.save && @comment.picture.user.notification_on_comment?


  end
# picture_path(@comment.picture_id)
  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
    redirect_to root_path
  end

  def edit
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = current_user.comments.find(params[:id])
    @comment.update(comment_update_params)
  end

  

  private

  def comment_params
    params.require(:comment).permit(:body).merge(picture_id: params[:picture_id])
  end

  def comment_update_params
    params.require(:comment).permit(:body)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
div id="comment-#{comment.id}"
  .row.no-gutters
    .col-2
      = image_tag comment.user.avatar.url, size: '40x40', class: 'rounded-circle'
    .col-9
      span.font-weight-bold.pr-1
        = comment.user.name
      = comment.body
    .col-1
      - if current_user&.own?(comment)
        = link_to comment_path(comment), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'}, remote: true do
          = icon 'far', 'trash-alt', class: 'fa-sm'
        = link_to edit_comment_path(comment), remote: true do
          = icon 'far', 'edit', class: 'fa-sm'
  hr

app/views/comments/_comments.html.slim
.comments-box
  = render comments

app/views/comments/_form.html.slim
= form_with model: [picture, comment], class: 'd-flex mb-0 flex-nowrap justify-content-between', remote: true do |f|
  = f.text_field :body, class: 'form-control input-comment-body', placeholder: 'コメント'
  = f.submit '投稿', class: 'btn btn-primary btn-raised'

app/views/comments/_modal_form.html.slim
.modal#comment-edit-modal
  .modal-dialog
    .modal-content
      .modal-header
        h5.modal-title コメント編集
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body
        = render 'form', picture: nil, comment: comment

app/views/comments/create.js.slim
- if @comment.errors.present?
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  | $('.comments-box').prepend("#{j render('comments/comment', comment: @comment)}");
  | $('.input-comment-body').val('');

app/views/comments/destroy.js.slim
| $('#comment-#{@comment.id}').remove();
| $("#comment-edit-modal").modal('show');

app/views/comments/edit.js.slim
| $("#modal-container").html("#{escape_javascript(render 'modal_form', comment: @comment)}");
| $("#comment-edit-modal").modal('show');

app/views/comments/update.js.slim
- if @comment.errors.present?
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  | $("#comment-#{@comment.id}").html("#{j render('comments/comment', comment: @comment)}");
  | $("#comment-edit-modal").modal('hide');