config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
# envは環境を確認するメソッド。↓はRailsが開発環境であるかを確認する。
  if Rails.env.development?
# letter_opener_webが送信されたメールを見れるようにしてくれる。
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  get 'comments/edit'
  root to: 'home#index'
  resources :pictures, shallow: true do
    collection do
      get :search
    end
    resources :comments
  end
  get    '/welcome', to: "sessions#new",     as: :welcome
  post   '/login',   to: "sessions#create",  as: :login
  delete '/logout',  to: "sessions#destroy", as: :logout
  resources :users, only: %i[index new create show]
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    patch :read, on: :member
  end
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Default: class_name: "Like"
  # Default: foreign_key: "user_id" LikeClassのuser_idとUserClassのidを紐づける
  # => "#{Model Name}s"
  has_many :like_pictures, through: :likes, source: :picture
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  # has_manyはメソッドを作るメソッドなので、active_relationshipでフォローしている人を探し出すメソッドになる
  # active_relationships => 自分からフォローするから能動的な関係性という意味でこの名前
  # class_nameを設定する理由は、デフォルトの挙動ではactive_relationshipモデルを探してしまうため
  # foreign_keyはRelationshipクラスのfollower_idとUserクラスのidを紐づけるという設定
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
# @user.active_relationships.map(&:followerd) => ユーザーがフォローしている人の一覧データ
# map(&:followerd)はハッシュからfollowerdという値を取り出すということを繰り返すというメソッド
# active_relationshipsのuser_idと@user.idが同じ(フォローしているユーザー)人のfollwerd（@userにフォローされている人）を全てとってくるメソッド（following）を作る
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :activities, dependent: :destroy

  scope :recent, ->(count) { order(created_at: :desc).limit(count) }

  def own?(object)
    id == object.user_id
  end

  def like(picture)
    like_pictures << picture
  end

  def unlike(picture)
    like_pictures.destroy(picture)
  end

  def like?(picture)
    like_pictures.include?(picture)
  end

  def follow(other_user)
    following << other_user
    # SQLとのやりとりをRailsの言語で書くので通常の挙動とは異なるが、配列に対して追加するような書き方をすることで、followingメソッドを発動させてfollowするというデータを作ることができる。
  end

  def unfollow(other_user)
    following.destroy(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed # feedはタイムラインのようなイメージ
    Picture.where("user_id IN (?) OR user_id = ?", following_ids, id)
  # Pictureの中から（）の条件のデータを問い合わせる。
  # "?"の部分には後ろにある引数が左から順に入っていく。DBのセキュリティ上の問題
  # following_idsはSQLのRuby言語で用意されているレールで、followingのidの集合をとってきてくれるメソッド
  # Pictureの中のuser_idが自分のフォローしている人のidか自分のidであればDBからとってくるという意味
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def index
    @users = User.all.page(params[:page]).order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to welcome_path
    else
      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to welcome_path, notice: "#{user.name}を削除しました"
  end

  def show
    @user = User.find(params[:id])
  end
  
  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
    )
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.slim
= link_to relationships_path(followed_id: user.id), class: 'btn btn-raised btn-outline-warning', method: :post, remote: true do
  | フォロー

app/views/users/_follow_area.html.slim
- if logged_in? && current_user.id != user.id
  div id="follow-area-#{user.id}"
    - if current_user.following?(user)
      = render 'users/unfollow', user: user
    - else
      = render 'users/follow', user: user

app/views/users/_unfollow.html.slim
= link_to relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), class: 'btn btn-warning btn-raised', method: :delete, remote: true do
  | アンフォロー

app/views/users/_user.html.slim
.user.mb-3.d-flex.justify-content-between
  = link_to user_path(user) do
    = image_tag user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
    = user.name
  = render 'users/follow_area', user: user
hr

app/views/users/index.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3.mb-3
      .card
        .card-body
          = render @users
    .col-md-6.col-12.offset-md-3
      = paginate @users

app/views/users/new.html.slim
.login-register-form
  .login-register-form-inner
    .card.mb-3
      = form_with model: @user, class: 'card-body', local: true do |f|
        = render 'shared/error_messages', object: @user
        .form-group
          = f.label :name, class: 'bmd-label-floating'
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :email, class: 'bmd-label-floating'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, class: 'bmd-label-floating'
          = f.password_field :password_confirmation, class: 'form-control'

        = f.submit '登録', class: 'btn btn-raised btn-primary'
    .card
      .card-body
        | アカウントをお持ちですか
        = link_to 'ログインする', login_path

app/views/users/show.html.slim
.container
  .row
    .col-md-10.offset-md-1
      .card
        .card-body
          - if current_user&.id == @user.id
            .text-center.mb-3
              = link_to 'プロフィール編集', edit_mypage_account_path, class: 'btn btn-raised btn-warning'
          .text-center.mb-3
            = image_tag 'black.jpg', size: '100x100', class: 'rounded-circle mr-1'
          .profile.text-center.mb-3
            = @user.name
          .text-center
            = render 'follow_area', user: @user
          hr
          .row
            = render partial: 'pictures/thumbnail_post', collection: @user.pictures