config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
# envは環境を確認するメソッド。↓はRailsが開発環境であるかを確認する。
  if Rails.env.development?
# letter_opener_webが送信されたメールを見れるようにしてくれる。
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  get 'comments/edit'
  root to: 'home#index'
  resources :pictures, shallow: true do
    collection do
      get :search
    end
    resources :comments
  end
  get    '/welcome', to: "sessions#new",     as: :welcome
  post   '/login',   to: "sessions#create",  as: :login
  delete '/logout',  to: "sessions#destroy", as: :logout
  resources :users, only: %i[index new create show]
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    patch :read, on: :member
  end
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/views/shared/_before_login_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    = render 'pictures/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to 'ポスト一覧', pictures_path, class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_commented_to_own_picture.html.slim
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.user.name, user_path(activity.subject.user)
  | があなたの
  object
    = link_to '投稿', picture_path(activity.subject.picture)
  | に
  object
    = link_to 'コメント', picture_path(activity.subject.picture, anchor: "comment-#{activity.subject.id}")
  | しました
  .ml-auto
    = l activity.created_at, format: :short

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    = render 'pictures/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to new_picture_path, class: 'nav-link' do
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        .dropdown
          a#dropdownMenuButton.nav-link.position-relative href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
            = icon 'far', 'heart', class: 'fa-lg'
            = render 'shared/unread_badge'
          #header-activities.dropdown-menu.dropdown-menu-right.m-0.p-0 aria-labelledby="dropdownMenuButton"
            = render 'shared/header_activities'

      li.nav-item
        = link_to user_path(current_user), class: 'nav-link' do
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_header_activities.html.slim
- if current_user.activities.present?
  - current_user.activities.recent(10).each do |activity|
    = render "shared/#{activity.action_type}", activity: activity
  - if current_user.activities.count > 10
    = link_to 'すべてみる', mypage_activities_path, class: 'dropdown-item justify-content-center'
- else
  .dropdown-item
    | お知らせはありません

app/views/shared/_modal.html.slim
#modal-container

app/views/shared/_unread_badge.html.slim
- if current_user.activities.unread.count > 0
  span.badge.badge-warning.navbar-badge.position-absolute style='top: 0; right:0;'
    = current_user.activities.unread.count