config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
# envは環境を確認するメソッド。↓はRailsが開発環境であるかを確認する。
  if Rails.env.development?
# letter_opener_webが送信されたメールを見れるようにしてくれる。
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  get 'comments/edit'
  root to: 'home#index'
  resources :pictures, shallow: true do
    collection do
      get :search
    end
    resources :comments
  end
  get    '/welcome', to: "sessions#new",     as: :welcome
  post   '/login',   to: "sessions#create",  as: :login
  delete '/logout',  to: "sessions#destroy", as: :logout
  resources :users, only: %i[index new create show]
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    patch :read, on: :member
  end
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploaders :image, ImageUploader
  has_many_attached :images
  belongs_to :user

  validates :images, presence: true
  validates :title, presence: true, length: { maximum: 1000 }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_one :activity, as: :subject, dependent: :destroy

# モデル名.where('カラム名 like ?','検索したい文字列') => ?には引数が左から順に入る。
  scope :body_contain, ->(word) { where('pictures.title LIKE ?', "%#{word}%") }
# joinsは複数のテーブルを内部結合するためのメソッド
  scope :comment_body_contain, ->(word) { joins(:comments).where('comments.body LIKE ?', "%#{word}%") }
  scope :name_contain, ->(word) { joins(:user).where('name LIKE ?', "%#{word}%") }
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index 
    @pictures = if current_user
                  current_user.feed.includes(:user).page(params[:page]).order(created_at: :desc)
                else
                  Picture.all.includes(:user).page(params[:page]).order(created_at: :desc)
                end
    @users = User.recent(5)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params.merge(user_id: current_user.id))
    if @picture.save
      redirect_to root_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def show
    @picture = Picture.find(params[:id])
    @comments = @picture.comments.includes(:user).order(created_at: :desc)
    @comment = Comment.new
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = current_user.pictures.find(params[:id])
    if @picture.update(picture_params)
      redirect_to picture_path, success: '投稿を更新しました'
    else
      flash.now[:danger] = '投稿の更新に失敗しました'
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to root_path, notice: "#{@picture.title}を削除しました"
  end

  def search
    @pictures = @search_form.search.includes(:user).page(params[:page])
  end
  
  private

  def picture_params
    params.require(:picture).permit(
      :title,
      images: []
    )
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.slim
= form_with model: picture, local: true do |f|
  = render 'shared/error_messages', object: picture
  .form-group
    = f.label :images
    = f.file_field :images, multiple: true, class: 'form-control'
    - picture.images.each do |image|
      = image_tag image, size: '100x100', class: 'image-thumbnail'
  .form-group
    = f.label :title
    = f.text_area :title, class: 'form-control'
  = f.submit class: 'btn btn-primary btn-raised'

app/views/pictures/_like.html.slim
= link_to likes_path(picture_id: picture.id), method: :post, remote: true do
  = icon 'far', 'heart', class: 'fa-lg'

app/views/pictures/_like_area.html.slim
div id="like_area-#{picture.id}"
  - if current_user.like?(picture)
    = render 'unlike', picture: picture
  - else
    = render 'like', picture: picture

app/views/pictures/_picture.html.slim
.card.mb-5.picture
  .card-header
    .d-flex.align-items-center
      = link_to user_path(picture.user) do
        = image_tag picture.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = picture.user.name
      - if current_user&.own?(picture)
        .ml-auto
          = link_to picture_path(picture), class: 'mr-3', method: :delete, data: { confirm: '本当に削除しますか？' } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_picture_path(picture) do
            = icon 'far', 'edit', class: 'fa-lg'
      - if current_user && !current_user.own?(picture)
        .ml-auto
          = render 'like_area', picture: picture
  = link_to picture_path(picture) do
    .swiper
      .swiper-wrapper
        - picture.images.each do |image|
          .swiper-slide
            = image_tag image, class: 'card-img-top'
      .swiper-pagination
  .card-body
    .card-text
      = picture.title

app/views/pictures/_search_form.html.slim
= form_with model: search_form, url: search_pictures_path, scope: :q, class: 'form-inline my-2 my-lg-0 mr-auto', method: :get, local: true do |f|
  = f.search_field :body, class: 'form-control mr-sm-2', placeholder: '本文'
  = f.search_field :comment_body, class: 'form-control mr-sm-2', placeholder: 'コメント'
  = f.search_field :name, class: 'form-control mr-sm-2', placeholder: 'ユーザー名'
  = f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

app/views/pictures/_thumbnail_post.html.slim
.col-md-4.mb-3
  = link_to picture_path(thumbnail_post), class: 'thumbs' do
    = image_tag thumbnail_post.images.first

app/views/pictures/_unlike.html.slim
= link_to like_path(current_user.likes.find_by(picture_id: picture.id)), method: :delete, remote: true do
  = icon 'fa', 'heart', class: 'fa-lg'

app/views/pictures/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-3
      .card
        .card-body
          = render 'form', picture: @picture

app/views/pictures/index.html.slim
.container
  .row
    .col-md-8.col-12p
      - if @pictures.present?
        = render @pictures
      - else
        .text-center.font-weight-bold
          | 投稿がありません
      = paginate @pictures
      = page_entries_info @pictures
    .col-md-4.col-12
      - if logged_in?
        .profile-box.mb-3
          = image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr-1'
          = link_to current_user.name, edit_mypage_account_path
      .users-box
        .card
          .card-header
            | ユーザー
          .card-body
            = render @users
          .card-footer
            = link_to 'すべて見る', users_path

app/views/pictures/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-body
          = render 'form', picture: @picture

app/views/pictures/search.html.slim
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        | 検索結果: #{@pictures.total_count}件
      = render @pictures
      = paginate @pictures

app/views/pictures/show.html.slim
.post-detail.card
  .image-box
    .swiper
      .swiper-wrapper
        - @picture.images.each do |image|
          .swiper-slide
            = image_tag image
      .swiper-pagination
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag @picture.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = @picture.user.name
        - if current_user&.own?(@picture)
          .ml-auto
            = link_to picture_path(@picture), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_picture_path(@picture) do
              = icon 'far', 'edit', class: 'fa-lg'
        - if current_user && !current_user.own?(@picture)
          .ml-auto
            = render 'like_area', picture: @picture
    hr.m-0
    .picture-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2
          = image_tag @picture.user.avatar.url, size: '40x40', class: 'rounded-circle'
        .col-10
          = simple_format(@picture.title)
      hr
      / コメント一覧
      = render 'comments/comments', comments: @comments
    hr.m-0
    .picture-comment.p-3
      = render 'comments/form', picture: @picture, comment: @comment